### ISSUE TITLE
Could you help me understand why I'm getting this error?

### ISSUE THREAD

**Issue by operator09** [Mitality/BodyHealth#3]
### Ask your question here

I have both BetterHud and PlaceholderAPI installed. However, after starting the server and connecting, I'm getting that error. What should I do?

 Could not pass event PlayerJoinEvent to BodyHealth v1.4.1
java.lang.NoClassDefFoundError: com/sk89q/worldguard/protection/flags/Flag
        at BodyHealth-1.4.1.jar/bodyhealth.listeners.BodyHealthListener.onPlayerJoin(BodyHealthListener.java:190) ~[BodyHealth-1.4.1.jar:?]
        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor326.execute(Unknown Source) ~[?:?]
        at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:77) ~[paper-mojangapi-1.21.1-R0.1-SNAPSHOT.jar:?]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[paper-mojangapi-1.21.1-R0.1-SNAPSHOT.jar:1.21.1-85-c5a1066]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[paper-mojangapi-1.21.1-R0.1-SNAPSHOT.jar:?]
        at io.papermc.paper.plugin.manager.PaperEventManager.callEvent(PaperEventManager.java:54) ~[paper-1.21.1.jar:1.21.1-85-c5a1066]
        at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.callEvent(PaperPluginManagerImpl.java:131) ~[paper-1.21.1.jar:1.21.1-85-c5a1066]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:628) ~[paper-mojangapi-1.21.1-R0.1-SNAPSHOT.jar:?]
        at net.minecraft.server.players.PlayerList.placeNewPlayer(PlayerList.java:347) ~[paper-1.21.1.jar:1.21.1-85-c5a1066]
        at net.minecraft.server.network.ServerConfigurationPacketListenerImpl.handleConfigurationFinished(ServerConfigurationPacketListenerImpl.java:173) ~[paper-1.21.1.jar:1.21.1-85-c5a1066]
        at net.minecraft.network.protocol.configuration.ServerboundFinishConfigurationPacket.handle(ServerboundFinishConfigurationPacket.java:22) ~[paper-1.21.1.jar:1.21.1-85-c5a1066]
        at net.minecraft.network.protocol.configuration.ServerboundFinishConfigurationPacket.handle(ServerboundFinishConfigurationPacket.java:13) ~[paper-1.21.1.jar:1.21.1-85-c5a1066]
        at net.minecraft.network.protocol.PacketUtils.lambda$ensureRunningOnSameThread$0(PacketUtils.java:56) ~[paper-1.21.1.jar:1.21.1-85-c5a1066]
        at net.minecraft.server.TickTask.run(TickTask.java:18) ~[paper-1.21.1.jar:1.21.1-85-c5a1066]
        at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:151) ~[paper-1.21.1.jar:1.21.1-85-c5a1066]
        at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:24) ~[paper-1.21.1.jar:1.21.1-85-c5a1066]
        at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1535) ~[paper-1.21.1.jar:1.21.1-85-c5a1066]
        at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:201) ~[paper-1.21.1.jar:1.21.1-85-c5a1066]
        at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:125) ~[paper-1.21.1.jar:1.21.1-85-c5a1066]
        at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1512) ~[paper-1.21.1.jar:1.21.1-85-c5a1066]
        at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1505) ~[paper-1.21.1.jar:1.21.1-85-c5a1066]
        at net.minecraft.util.thread.BlockableEventLoop.managedBlock(BlockableEventLoop.java:135) ~[paper-1.21.1.jar:1.21.1-85-c5a1066]
        at net.minecraft.server.MinecraftServer.managedBlock(MinecraftServer.java:1464) ~[paper-1.21.1.jar:1.21.1-85-c5a1066]
        at net.minecraft.server.MinecraftServer.waitUntilNextTick(MinecraftServer.java:1471) ~[paper-1.21.1.jar:1.21.1-85-c5a1066]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1316) ~[paper-1.21.1.jar:1.21.1-85-c5a1066]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:329) ~[paper-1.21.1.jar:1.21.1-85-c5a1066]
        at java.base/java.lang.Thread.run(Thread.java:1583) ~[?:?]
Caused by: java.lang.ClassNotFoundException: com.sk89q.worldguard.protection.flags.Flag
        at org.bukkit.plugin.java.PluginClassLoader.loadClass0(PluginClassLoader.java:197) ~[paper-mojangapi-1.21.1-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.java.PluginClassLoader.loadClass(PluginClassLoader.java:164) ~[paper-mojangapi-1.21.1-R0.1-SNAPSHOT.jar:?]
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:526) ~[?:?]
        ... 27 more

**Comment by operator09** [comment]
Thank you! The error code has disappeared, but I'm wondering why it shows up like in the screenshot below? Does it require a separate resource pack? Also, since I added this plugin, players can't die at all—could that be related to this?
![image](https://github.com/user-attachments/assets/5ceb35a1-9f27-4a04-a4fb-91621ef89352)

**Comment by operator09** [comment]
Thank you so much! I've resolved all the other issues! However, as shown in the picture below, it keeps happening to me, while other players are not experiencing this. Why could that be? 
![image](https://github.com/user-attachments/assets/c2192aaa-a83a-4a9c-8a50-9a2f3880d8ea)

**Comment by operator09** [comment]
I changed it to false using LuckPerms, but the problem is still the same
![image](https://github.com/user-attachments/assets/61af234a-0cc3-4914-baf5-25bb6ed180df)
Now, even the health of other players has changed to .NAN. I have no idea what the problem is
![image](https://github.com/user-attachments/assets/26245185-c941-40ff-ae4f-74db8ad54854)

**Comment by operator09** [comment]
I just tested it, and after dying, a specific body part changes to NAN.

this is my server log
[19:29:41] [Server thread/WARN]: [BodyHealthDebug - BodyHealthListener] Player operator09 regenerated 1.0 HP
[19:29:43] [Server thread/WARN]: [BodyHealthDebug - BodyHealthListener] Player operator09 was hit by an arrow on HEAD with 4.0 damage.
[19:29:45] [Server thread/WARN]: [BodyHealthDebug - BodyHealthListener] Player operator09 regenerated 1.0 HP
[19:29:46] [Server thread/WARN]: [BodyHealthDebug - BodyHealthListener] Player operator09 was hit by an arrow on HEAD with 4.0 damage.
[19:29:50] [Server thread/WARN]: [BodyHealthDebug - BodyHealthEffects] (HEAD) Killed player operator09
[19:29:50] [Server thread/WARN]: [BodyHealthDebug - BodyHealthListener] Player operator09 was hit by an arrow on HEAD with 4.0 damage.
[19:29:50] [Server thread/INFO]: operator09 was shot by Skeleton
[19:30:01] [Server thread/WARN]: [BodyHealthDebug - BodyHealthListener] Player operator09 was hit by an arrow on BODY with NaN damage.
[19:30:04] [Server thread/WARN]: [BodyHealthDebug - BodyHealthListener] Player operator09 was hit by an arrow on HEAD with NaN damage.
[19:30:07] [Server thread/WARN]: [BodyHealthDebug - BodyHealthListener] Player operator09 was hit by an arrow on HEAD with NaN damage.
[19:30:13] [Server thread/WARN]: [BodyHealthDebug - BodyHealthListener] Player operator09 was hit by an arrow on HEAD with NaN damage.
[19:30:16] [Server thread/WARN]: [BodyHealthDebug - BodyHealthListener] Player operator09 was hit by an arrow on HEAD with NaN damage.
[19:30:18] [Server thread/WARN]: [BodyHealthDebug - BodyHealthListener] Player operator09 was hit by an arrow on HEAD with NaN damage.
[19:30:20] [Server thread/WARN]: [BodyHealthDebug - BodyHealthListener] Player operator09 was hit by an arrow on HEAD with NaN damage.
[19:30:22] [Server thread/WARN]: [BodyHealthDebug - BodyHealthListener] Player operator09 was hit by an arrow on HEAD with NaN damage.
[19:30:24] [Server thread/WARN]: [BodyHealthDebug - BodyHealthListener] Player operator09 was hit by an arrow on HEAD with NaN damage.
[19:30:25] [Server thread/INFO]: operator09 issued server command: /bh get operator09 ARM_LEFT
